# Generated by Django 4.2.6 on 2024-02-27 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone_no', models.CharField(max_length=20, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('primary_email', models.EmailField(max_length=62, null=True)),
                ('email', models.EmailField(blank=True, max_length=62)),
                ('address', models.TextField(null=True)),
                ('top_title', models.CharField(max_length=255, null=True)),
                ('logo', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('google_map', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Address & Logo',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('messages', models.TextField(null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint_name', models.CharField(max_length=30, null=True)),
                ('messages', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial / Review',
            },
        ),
    ]
