# Generated by Django 4.2.6 on 2024-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_address',
            old_name='logo',
            new_name='footer_logo',
        ),
        migrations.AddField(
            model_name='contact_address',
            name='header_logo',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
