# Generated by Django 4.2.6 on 2024-02-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_openhoure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhoure',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openhoure',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
