# Generated by Django 4.2.6 on 2024-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_openhoure_end_time_alter_openhoure_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('detailes', models.CharField(max_length=250, null=True)),
                ('full_detailes', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'About & sliders',
            },
        ),
    ]
