# Generated by Django 4.2.6 on 2024-02-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slider_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
