# Generated by Django 4.2.6 on 2024-02-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_about_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, null=True)),
                ('picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('sort_details', models.CharField(max_length=31, null=True)),
                ('facebook_link', models.CharField(default='Write..', max_length=127)),
                ('twitter_link', models.CharField(default='Write..', max_length=127)),
                ('google_link', models.CharField(default='Write..', max_length=127)),
                ('instagram_link', models.CharField(default='Write..', max_length=127)),
            ],
            options={
                'verbose_name_plural': 'Team Members List',
            },
        ),
    ]
