# Generated by Django 4.2.6 on 2024-02-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_teammembers_sort_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='sort_details',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
