# Generated by Django 4.2.6 on 2024-02-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_teammembers_sort_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('values', models.CharField(max_length=15, null=True)),
                ('icone', models.TextField(max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Fun-Factor',
            },
        ),
    ]
