# Generated by Django 4.2.6 on 2024-02-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_funfactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funfactor',
            name='icone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
