# Generated by Django 4.2.6 on 2024-02-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_funfactor_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseUs_title', models.TextField(null=True)),
                ('choose_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('chef_title', models.CharField(max_length=255, null=True)),
                ('total_tables', models.CharField(max_length=15, null=True)),
                ('tables_detailes', models.CharField(max_length=255, null=True)),
                ('clean_detailes', models.CharField(max_length=255, null=True)),
                ('our_chefs_title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'About Fun-Factor',
            },
        ),
    ]
