# Generated by Django 4.2.6 on 2024-02-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_chooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField(max_length=63, null=True)),
                ('blog_image', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('date', models.DateField()),
                ('top_details', models.TextField(null=True)),
                ('details2', models.TextField(null=True)),
                ('banner_details', models.TextField(null=True)),
                ('buttom_details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog List',
            },
        ),
        migrations.AlterModelOptions(
            name='chooseus',
            options={'verbose_name_plural': 'Choose Us'},
        ),
    ]
