# Generated by Django 4.2.6 on 2024-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_blog_alter_chooseus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
