# Generated by Django 4.2.6 on 2024-02-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_blog_blog_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogList',
        ),
    ]
