# Generated by Django 4.2.6 on 2024-02-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_rename_blog_bloglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglist',
            name='home_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bloglist',
            name='top_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
