# Generated by Django 4.2.6 on 2024-02-28 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_bloglist_home_image_bloglist_top_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('reservation_date', models.DateField(null=True)),
                ('reservation_time', models.TimeField(null=True)),
                ('total_person', models.CharField(max_length=15, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Reservation Clint',
            },
        ),
    ]
