# Generated by Django 4.2.6 on 2024-02-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=27, null=True)),
                ('dish_picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('dish_price', models.CharField(max_length=27, null=True)),
                ('details', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Our Popular Dishes',
            },
        ),
    ]
