# Generated by Django 4.2.6 on 2024-02-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_populardishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27, null=True)),
            ],
            options={
                'verbose_name_plural': 'MenuCategory',
            },
        ),
        migrations.CreateModel(
            name='DishesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=27, null=True)),
                ('dish_title', models.CharField(max_length=27, null=True)),
                ('dish_picture', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('dish_price', models.CharField(max_length=27, null=True)),
                ('details', models.TextField(null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucategory')),
            ],
            options={
                'verbose_name_plural': 'All Menu',
            },
        ),
    ]
