# Generated by Django 4.2.6 on 2024-02-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_menucategory_dishesmenu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'Menu Category list'},
        ),
        migrations.RenameField(
            model_name='dishesmenu',
            old_name='name',
            new_name='category_name',
        ),
    ]
