# Generated by Django 4.2.6 on 2024-02-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_title', models.CharField(max_length=255, null=True)),
                ('popular_dish_title', models.CharField(max_length=255, null=True)),
                ('menu_title', models.CharField(max_length=255, null=True)),
                ('booking_table_title', models.CharField(max_length=255, null=True)),
                ('blog_title', models.CharField(max_length=255, null=True)),
                ('newsletter', models.CharField(max_length=255, null=True)),
                ('choose_title', models.CharField(max_length=255, null=True)),
                ('chefs_title', models.CharField(max_length=255, null=True)),
                ('contact_title', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'All Page Sections Titles',
            },
        ),
        migrations.AlterModelOptions(
            name='dishesmenu',
            options={'verbose_name_plural': 'All Menu List'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name_plural': 'All Menu Category'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservation Booking Clint'},
        ),
    ]
