# Generated by Django 4.2.6 on 2024-02-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_allsections_alter_dishesmenu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allsections',
            name='chefs_title',
        ),
        migrations.RemoveField(
            model_name='allsections',
            name='choose_title',
        ),
        migrations.RemoveField(
            model_name='allsections',
            name='contact_title',
        ),
    ]
