# Generated by Django 4.2.6 on 2024-03-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_allsections_login_title_allsections_register_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='populardishes',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucategory'),
        ),
        migrations.AddField(
            model_name='populardishes',
            name='description1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='populardishes',
            name='description2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='populardishes',
            name='details_picture',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='populardishes',
            name='dish_title',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
