# Generated by Django 4.2.6 on 2024-03-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_populardishes_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blog_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.bloglist')),
            ],
            options={
                'verbose_name_plural': 'Blog Comment',
            },
        ),
    ]
