# Generated by Django 4.2.6 on 2024-03-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CommentDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('dish_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.populardishes')),
            ],
            options={
                'verbose_name_plural': 'Dish Reviews',
            },
        ),
    ]
