# Generated by Django 4.2.6 on 2024-03-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_commentblog_active_commentdish'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsections',
            name='recent_food_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
